#############################
#		Matte Black Theme		#
#############################
# Unified rice preset configuration

bg="#121212"
fg="#e0e0e0"

black="#1e1e1e"
red="#ff5252"
green="#69f0ae"
yellow="#ffd740"
blue="#40c4ff"
magenta="#e040fb"
cyan="#18ffff"
white="#e0e0e0"

blackb="#616161"
redb="#ff5252"
greenb="#69f0ae"
yellowb="#ffd740"
blueb="#40c4ff"
magentab="#e040fb"
cyanb="#18ffff"
whiteb="#ffffff"

accent_color="#00adb5"
NORMAL_BC="#333333"
FOCUSED_BC="#00adb5"

# Terminal font & size
term_font_size="10"
term_font_name="JetBrainsMono Nerd Font"

# Gtk theme
gtk_theme="Adwaita-dark"
gtk_icons="Papirus-Dark"
gtk_cursor="Qogirr"

# Wallpaper
ENGINE="Default"
DEFAULT_WALL="$HOME/wm/themes/presets/matte-black/wallpapers/nord.jpg"
