#############################
#		Nord Theme		#
#############################
# Unified rice preset configuration

bg="#2e3440"
fg="#d8dee9"

black="#3b4252"
red="#bf616a"
green="#a3be8c"
yellow="#ebcb8b"
blue="#81a1c1"
magenta="#b48ead"
cyan="#88c0d0"
white="#e5e9f0"

blackb="#4c566a"
redb="#bf616a"
greenb="#a3be8c"
yellowb="#ebcb8b"
blueb="#81a1c1"
magentab="#b48ead"
cyanb="#8fbcbb"
whiteb="#eceff4"

accent_color="#88c0d0"
NORMAL_BC="#4c566a"
FOCUSED_BC="#88c0d0"

# Terminal font & size
term_font_size="10"
term_font_name="JetBrainsMono Nerd Font"

# Gtk theme
gtk_theme="Adwaita-dark"
gtk_icons="Papirus-Custom"
gtk_cursor="Qogirr"

# Wallpaper
ENGINE="Default"
DEFAULT_WALL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/wallpapers/nord.jpg"
