#* Appearance
color_theme = "nord"
theme_background = True
truecolor = True
rounded_corners = True
vim_keys = False

#* Layout
shown_boxes = "cpu mem net proc"
update_ms = 2000
cpu_bottom = False
mem_below_net = False

#* CPU
check_temp = True
show_coretemp = True
temp_scale = "celsius"
cpu_single_graph = False
show_uptime = True
base_10_sizes = False
clock_format = "%X"

#* Processes
proc_sorting = "mem lazy"
proc_tree = False
proc_reversed = False
proc_per_core = False
proc_mem_bytes = True

