#!/usr/bin/env bash

[[ $# -eq 0 ]] && exit 0

if [[ "$1" == "-t" ]]; then
    shift
    exec footclient "$@" 2>/dev/null || exec foot "$@" 2>/dev/null || exec alacritty -e "$@"
fi

cmd="${1##*/}"

case "$cmd" in
    foot|footclient|alacritty|kitty|wezterm|ghostty|xterm)
        exec "$@"
        ;;
    nvim|vim|vi|nano|micro|hx|helix|emacs|\
    htop|btop|top|btm|nmtui|bluetui|wiremix|alsamixer|\
    ranger|yazi|lf|nnn|vifm|mc|\
    lazygit|lazydocker|k9s|gitui|\
    ncdu|gdu|dua|dust|\
    cmus|ncmpcpp|mocp|\
    fzf|tmux|screen|zellij|\
    man|less|more|bat|\
    fastfetch|neofetch|pfetch|onefetch)
        if [[ "$cmd" == "fastfetch" || "$cmd" == "neofetch" || "$cmd" == "pfetch" || "$cmd" == "onefetch" ]]; then
            exec footclient -H "$@" 2>/dev/null || exec foot -H "$@" 2>/dev/null || exec alacritty --hold -e "$@"
        else
            exec footclient "$@" 2>/dev/null || exec foot "$@" 2>/dev/null || exec alacritty -e "$@"
        fi
        ;;
esac

exec "$@"
