#############################
#		Everforest Theme		#
#############################
# Unified rice preset configuration

bg="#2b3339"
fg="#d3c6aa"

black="#323c41"
red="#e67e80"
green="#a7c080"
yellow="#dbbc7f"
blue="#7fbbb3"
magenta="#d699b6"
cyan="#83c092"
white="#d3c6aa"

blackb="#5c6a72"
redb="#e67e80"
greenb="#a7c080"
yellowb="#dbbc7f"
blueb="#7fbbb3"
magentab="#d699b6"
cyanb="#83c092"
whiteb="#9da9a0"

accent_color="#a7c080"
NORMAL_BC="#4f5b58"
FOCUSED_BC="#a7c080"

# Terminal font & size
term_font_size="10"
term_font_name="JetBrainsMono Nerd Font"

# Gtk theme
gtk_theme="Adwaita-dark"
gtk_icons="Papirus-Dark"
gtk_cursor="Qogirr"

# Wallpaper
ENGINE="Default"
DEFAULT_WALL="$HOME/wm/themes/presets/everforest/wallpapers/forest.jpg"
