#############################
#		Dracula Theme		#
#############################
# Unified rice preset configuration

bg="#282a36"
fg="#f8f8f2"

black="#21222c"
red="#ff5555"
green="#50fa7b"
yellow="#f1fa8c"
blue="#bd93f9"
magenta="#ff79c6"
cyan="#8be9fd"
white="#f8f8f2"

blackb="#6272a4"
redb="#ff6e6e"
greenb="#69ff94"
yellowb="#ffffa5"
blueb="#d6acff"
magentab="#ff92df"
cyanb="#a4ffff"
whiteb="#ffffff"

accent_color="#bd93f9"
NORMAL_BC="#6272a4"
FOCUSED_BC="#bd93f9"

# Terminal font & size
term_font_size="10"
term_font_name="JetBrainsMono Nerd Font"

# Gtk theme
gtk_theme="Adwaita-dark"
gtk_icons="Papirus-Custom"
gtk_cursor="Qogirr"

# Wallpaper
ENGINE="Default"
DEFAULT_WALL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/wallpapers/mountain.jpg"
