#############################
#		Poimandres Theme	#
#############################
# Unified rice preset configuration

bg="#1b1e28"
fg="#e4f0fb"

black="#1b1e28"
red="#d0679d"
green="#5de4c7"
yellow="#fffac2"
blue="#89ddff"
magenta="#fcc5e9"
cyan="#add7ff"
white="#e4f0fb"

blackb="#506477"
redb="#d0679d"
greenb="#5de4c7"
yellowb="#fffac2"
blueb="#add7ff"
magentab="#fae4fc"
cyanb="#89ddff"
whiteb="#ffffff"

accent_color="#5de4c7"
NORMAL_BC="#303340"
FOCUSED_BC="#5de4c7"

# Terminal font & size
term_font_size="10"
term_font_name="JetBrainsMono Nerd Font"

# Gtk theme
gtk_theme="Adwaita-dark"
gtk_icons="Papirus-Custom"
gtk_cursor="Qogirr"

# Wallpaper
ENGINE="Default"
DEFAULT_WALL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/wallpapers/mountain.jpg"
