# Ly Display Manager Configuration
# Target: /etc/ly/config.ini

animate = false
animation = 0
asterisk = *
bg = 0
fg = 7
blank_box = true
blank_password = true
hide_borders = false
margin_box_h = 2
margin_box_v = 1
input_len = 34
lang = en

save = true
load = true
save_file = /etc/ly/save
default_input = 2

session_log = null

waylandsessions = /usr/share/wayland-sessions
wayland_cmd = /etc/ly/wsetup.sh
service_name = login

shutdown_cmd = /sbin/shutdown -h now
restart_cmd = /sbin/shutdown -r now
tty = 2
