#!/bin/bash

get_signal() {
  nmcli -t -f active,signal dev wifi 2>/dev/null | grep '^yes:' | cut -d: -f2 | head -1
}

get_ssid() {
  nmcli -t -f active,ssid dev wifi 2>/dev/null | grep '^yes:' | cut -d: -f2 | head -1
}

icon() {
  local wf
  wf=$(get_signal)
  if [[ -z "$wf" || "$wf" -le 0 ]]; then
    echo "images/wifi-off.svg"
  elif [[ $wf -le 30 ]]; then
    echo "images/wifi-low.svg"
  elif [[ $wf -le 60 ]]; then
    echo "images/wifi-medium.svg"
  else
    echo "images/wifi-high.svg"
  fi
}

percentage() {
  local wf
  wf=$(get_signal)
  if [[ -n "$wf" && "$wf" -gt 0 ]]; then
    echo "${wf}%"
  else
    echo "0%"
  fi
}

name() {
  local ssid
  ssid=$(get_ssid)
  if [[ -n "$ssid" ]]; then
    echo "$ssid"
  else
    echo "Disconnected"
  fi
}

case "${1:-}" in
  icon) icon ;;
  percentage) percentage ;;
  name) name ;;
  *) icon ;;
esac
