#############################
#		Rose Pine Theme		#
#############################
# Unified rice preset configuration

bg="#191724"
fg="#e0def4"

black="#26233a"
red="#eb6f92"
green="#31748f"
yellow="#f6c177"
blue="#9ccfd8"
magenta="#c4a7e7"
cyan="#ebbcba"
white="#e0def4"

blackb="#6e6a86"
redb="#eb6f92"
greenb="#31748f"
yellowb="#f6c177"
blueb="#9ccfd8"
magentab="#c4a7e7"
cyanb="#ebbcba"
whiteb="#e0def4"

accent_color="#ebbcba"
NORMAL_BC="#403d52"
FOCUSED_BC="#ebbcba"

# Terminal font & size
term_font_size="10"
term_font_name="JetBrainsMono Nerd Font"

# Gtk theme
gtk_theme="Adwaita-dark"
gtk_icons="Papirus-Dark"
gtk_cursor="Qogirr"

# Wallpaper
ENGINE="Default"
DEFAULT_WALL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/wallpapers/mountain.jpg"
