#!/usr/bin/env bash

command -v mmsg >/dev/null 2>&1 || exit 1

if command -v jq >/dev/null 2>&1; then
    mmsg get all-clients 2>/dev/null |
        jq -r '.clients[] | select(.is_minimized == false) | "\(.x),\(.y) \(.width)x\(.height)"'
fi
