color_theme = "wm"
theme_background = false
truecolor = true
force_tty = false
rounded_corners = false
terminal_sync = true
graph_symbol = "braille"
update_ms = 2000

shown_boxes = "proc"

proc_sorting = "cpu lazy"
proc_reversed = false
proc_tree = false
proc_colors = true
proc_gradient = false
proc_per_core = false
proc_mem_bytes = true
proc_cpu_graphs = false

show_uptime = true
show_cpu_watts = false
check_temp = true
show_coretemp = false
temp_scale = "celsius"
show_cpu_freq = true

clock_format = "%X"
background_update = true

mem_graphs = false
show_swap = true
show_disks = false
show_io_stat = false

show_battery = true
show_battery_watts = false

log_level = "ERROR"
save_config_on_exit = false
