#############################
#		Kanagawa Theme		#
#############################
# Unified rice preset configuration

bg="#1f1f28"
fg="#dcd7ba"

black="#16161d"
red="#c34043"
green="#76946a"
yellow="#c0a36e"
blue="#7e9cd8"
magenta="#957fb8"
cyan="#6a9589"
white="#c8c093"

blackb="#727169"
redb="#e82424"
greenb="#98bb6c"
yellowb="#e6c384"
blueb="#7fb4ca"
magentab="#938aa9"
cyanb="#7aa89f"
whiteb="#dcd7ba"

accent_color="#7e9cd8"
NORMAL_BC="#363646"
FOCUSED_BC="#7e9cd8"

# Terminal font & size
term_font_size="10"
term_font_name="JetBrainsMono Nerd Font"

# Gtk theme
gtk_theme="Adwaita-dark"
gtk_icons="Papirus-Dark"
gtk_cursor="Qogirr"

# Wallpaper
ENGINE="Default"
DEFAULT_WALL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/wallpapers/mountain.jpg"
