#!/usr/bin/env python3
"""
theme-engine.py: Central Theme Engine for Void Linux + MangoWC rice.
Compiles and applies theme tokens across:
- Waybar (CSS & JSON)
- Rofi (RASI)
- Foot (INI)
- Mako (config)
- MangoWC (config.conf)
- GTK 3 & 4 (gtk.css)
- btop (wm.theme)
- Fastfetch (config.jsonc)
Dispatches live reloads for zero-restart theme transitions.
"""
import sys
import os
import json
import re
import subprocess
import glob

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(SCRIPT_DIR)
THEMES_DIR = os.path.join(REPO_DIR, "themes")
DEFS_DIR = os.path.join(THEMES_DIR, "defs")
MANGO_CONF = os.path.join(REPO_DIR, "mango", "config.conf")
MAKO_CONF = os.path.join(REPO_DIR, "mako", "config")
GTK_CSS = os.path.join(REPO_DIR, "gtk-3.0", "gtk.css")
FOOT_CONF = os.path.join(REPO_DIR, "terminal", "foot", "foot.ini")
BTOP_THEMES_DIR = os.path.expanduser("~/.config/btop/themes")
BTOP_CONF = os.path.expanduser("~/.config/btop/btop.conf")
FASTFETCH_CONF = os.path.expanduser("~/.config/fastfetch/config.jsonc")
CACHE_DIR = os.path.expanduser("~/.cache")

def strip_hash(color_str):
    if color_str and color_str.startswith("#"):
        return color_str[1:]
    return color_str or "000000"

def to_argb_hex(color_str, alpha="ff"):
    h = strip_hash(color_str).lower()
    return f"0x{h}{alpha}"

def load_theme(theme_id):
    if theme_id == "dynamic":
        dyn_file = os.path.join(THEMES_DIR, "dynamic.json")
        if os.path.isfile(dyn_file):
            with open(dyn_file, "r") as f:
                return json.load(f)
        else:
            # Fallback to current palette if dynamic.json does not exist yet
            pal_file = os.path.join(THEMES_DIR, "palette.json")
            if os.path.isfile(pal_file):
                with open(pal_file, "r") as f:
                    return json.load(f)
            raise FileNotFoundError("Dynamic theme palette not found. Run theme-from-wallpaper first.")

    theme_file = os.path.join(DEFS_DIR, f"{theme_id}.json")
    if not os.path.isfile(theme_file):
        raise FileNotFoundError(f"Theme '{theme_id}' not found in {DEFS_DIR}")
    with open(theme_file, "r") as f:
        return json.load(f)

def generate_waybar_css(t):
    lines = [
        "/* ==========================================================================",
        f" * Waybar Theme Tokens - {t.get('name', 'Theme')}",
        " * Generated by central theme-engine",
        " * ========================================================================== */",
        f"@define-color capsule_bg {t.get('capsule_bg', '#242436')};",
        f"@define-color capsule_hover {t.get('capsule_hover', '#2d2d44')};",
        f"@define-color capsule_fg {t.get('capsule_fg', '#D8DEE9')};",
        f"@define-color border_color {t.get('border', '#3B4252')};",
        f"@define-color clock_color {t.get('clock', '#F5C2E7')};",
        f"@define-color ram_color {t.get('ram', '#CBA6F7')};",
        f"@define-color keyviz_color {t.get('keyviz', '#89DCEB')};",
        f"@define-color recorder_color {t.get('recorder', '#D894A1')};",
        f"@define-color ws_focused {t.get('ws_focused', '#B4BEFE')};",
        f"@define-color ws_occupied {t.get('ws_occupied', '#B090D7')};",
        f"@define-color ws_empty {t.get('ws_empty', '#89DCEB')};",
        f"@define-color ws_urgent {t.get('ws_urgent', '#D894A1')};",
        f"@define-color bt_color {t.get('bt', '#B192DA')};",
        f"@define-color net_color {t.get('net', '#F9E2AF')};",
        f"@define-color vol_color {t.get('vol', '#EBA0AC')};",
        f"@define-color bat_color {t.get('bat', '#79BFCE')};",
        f"@define-color session_color {t.get('session', '#F38BA7')};",
        f"@define-color accent {t.get('accent', '#B4BEFE')};",
        f"@define-color bg {t.get('background', '#1e1e2e')};",
        f"@define-color fg {t.get('foreground', '#cdd6f4')};",
        ""
    ]
    return "\n".join(lines)

def generate_rofi_rasi(t):
    lines = [
        "/**",
        f" * Rofi Palette Tokens - {t.get('name', 'Theme')}",
        " * Generated by central theme-engine",
        " **/",
        "* {",
        f"    background:                  {t.get('background', '#2E3440')}EE;",
        f"    background-alt:              {t.get('capsule_bg', '#242933')}FF;",
        f"    background-surface:          {t.get('capsule_hover', '#3B4252')}FF;",
        f"    border-color:                {t.get('border', '#4C566A')}FF;",
        f"    foreground:                  {t.get('foreground', '#D8DEE9')}FF;",
        f"    foreground-muted:            {t.get('border', '#4C566A')}FF;",
        f"    foreground-bright:           {t.get('color15', t.get('foreground', '#ECEFF4'))}FF;",
        f"    selected:                    {t.get('accent', '#88C0D0')}FF;",
        f"    selected-fg:                 {t.get('background', '#2E3440')}FF;",
        f"    accent:                      {t.get('accent', '#81A1C1')}FF;",
        f"    teal:                        {t.get('bat', '#8FBCBB')}FF;",
        f"    urgent:                      {t.get('ws_urgent', '#BF616A')}FF;",
        f"    active:                      {t.get('vol', '#A3BE8C')}FF;",
        f"    warning:                     {t.get('net', '#EBCB8B')}FF;",
        f"    capsule-bg:                  {t.get('capsule_bg', '#242933')}FF;",
        f"    capsule-hover:               {t.get('capsule_hover', '#3B4252')}FF;",
        f"    capsule-fg:                  {t.get('capsule_fg', '#D8DEE9')}FF;",
        "}"
    ]
    return "\n".join(lines) + "\n"

def generate_foot_ini(t):
    lines = [
        "# -*- conf -*-",
        f"# Foot Terminal Color Palette - {t.get('name', 'Theme')}",
        "# Generated by central theme-engine",
        "",
        "[colors-dark]",
        f"background = {strip_hash(t.get('background', '#2e3440'))}",
        f"foreground = {strip_hash(t.get('foreground', '#d8dee9'))}",
        f"cursor = {strip_hash(t.get('background', '#2e3440'))} {strip_hash(t.get('cursor', t.get('foreground', '#d8dee9')))}",
        f"selection-background = {strip_hash(t.get('selection_bg', t.get('border', '#4c566a')))}",
        f"selection-foreground = {strip_hash(t.get('selection_fg', t.get('foreground', '#eceff4')))}",
        ""
    ]
    for i in range(8):
        k = f"color{i}"
        val = strip_hash(t.get(k, '#000000'))
        lines.append(f"regular{i} = {val}")
    lines.append("")
    for i in range(8, 16):
        k = f"color{i}"
        val = strip_hash(t.get(k, '#ffffff'))
        lines.append(f"bright{i-8} = {val}")
    lines.append("")
    return "\n".join(lines)

def generate_mako_conf(t):
    accent = t.get('accent', '#88C0D0')
    bg = t.get('capsule_bg', '#242933')
    fg = t.get('capsule_fg', '#D8DEE9')
    border = t.get('border', '#4C566A')
    urgent = t.get('ws_urgent', '#BF616A')

    content = f"""# Mako Notification Daemon Configuration - {t.get('name', 'Theme')}
# Generated by central theme-engine

# Appearance
font=Maple Mono NF 10
background-color={bg}F2
text-color={fg}
width=350
height=110
margin=14
padding=12
border-size=1
border-color={accent}
border-radius=6

# Layout & Behavior
icons=1
max-icon-size=48
default-timeout=5000
ignore-timeout=0
group-by=summary

# Progress bar styling for OSD (volume, brightness)
progress-color={accent}FF

# Urgency Specific Styles
[urgency=low]
border-color={border}
default-timeout=3000

[urgency=normal]
border-color={accent}
default-timeout=5000

[urgency=critical]
border-color={urgent}
text-color=#FFFFFF
default-timeout=0
"""
    return content

def generate_shell_env(t):
    lines = [
        f"# Theme Environment Tokens - {t.get('name', 'Theme')}",
        f"export WM_THEME='{t.get('id', 'default')}'",
        f"export WM_THEME_NAME='{t.get('name', 'Default')}'",
        f"export WM_BG='{t.get('background', '#2e3440')}'",
        f"export WM_FG='{t.get('foreground', '#d8dee9')}'",
        f"export WM_ACCENT='{t.get('accent', '#88c0d0')}'",
        f"export WM_BORDER='{t.get('border', '#4c566a')}'",
        f"export WM_CAPSULE_BG='{t.get('capsule_bg', '#242933')}'",
        f"export WM_CAPSULE_HOVER='{t.get('capsule_hover', '#3b4252')}'",
        f"export WM_CAPSULE_FG='{t.get('capsule_fg', '#d8dee9')}'",
        f"export WM_WALLPAPER='{t.get('wallpaper', '')}'"
    ]
    return "\n".join(lines) + "\n"

def update_mango_conf(t):
    if not os.path.isfile(MANGO_CONF):
        return
    with open(MANGO_CONF, "r") as f:
        conf = f.read()

    bg_argb = to_argb_hex(t.get('background', '#2e3440'), "ff")
    border_argb = to_argb_hex(t.get('border', '#4c566a'), "ff")
    focus_argb = to_argb_hex(t.get('accent', '#88c0d0'), "ff")
    max_argb = to_argb_hex(t.get('accent_alt', t.get('accent', '#81a1c1')), "ff")
    urgent_argb = to_argb_hex(t.get('ws_urgent', '#bf616a'), "ff")
    scratch_argb = to_argb_hex(t.get('capsule_hover', '#3b4252'), "cc")
    global_argb = to_argb_hex(t.get('clock', '#b48ead'), "aa")
    overlay_argb = to_argb_hex(t.get('accent', '#8fbcbb'), "ff")

    color_block = f"""# {t.get('name', 'Theme')} Palette Colors (ARGB)
rootcolor = {bg_argb}
bordercolor = {border_argb}
focuscolor = {focus_argb}
maximizescreencolor = {max_argb}
urgentcolor = {urgent_argb}
scratchpadcolor = {scratch_argb}
globalcolor = {global_argb}
overlaycolor = {overlay_argb}"""

    # Replace block between border_radius and cursor or existing color block
    pattern = r"# .* Palette Colors \(ARGB\)[\s\S]*?overlaycolor = 0x[0-9a-fA-F]+"
    if re.search(pattern, conf):
        new_conf = re.sub(pattern, color_block, conf)
    else:
        # Fallback regex matching individual directives
        pattern2 = r"rootcolor = 0x[0-9a-fA-F]+[\s\S]*?overlaycolor = 0x[0-9a-fA-F]+"
        if re.search(pattern2, conf):
            new_conf = re.sub(pattern2, color_block, conf)
        else:
            return

    with open(MANGO_CONF, "w") as f:
        f.write(new_conf)

def update_gtk_css(t):
    bg = t.get('background', '#2e3440')
    fg = t.get('foreground', '#d8dee9')
    accent = t.get('accent', '#88c0d0')
    border = t.get('border', '#4c566a')
    capsule_bg = t.get('capsule_bg', '#242933')
    capsule_hover = t.get('capsule_hover', '#3b4252')
    capsule_fg = t.get('capsule_fg', '#d8dee9')
    sel_bg = t.get('selection_bg', accent)
    sel_fg = t.get('selection_fg', bg)
    urgent = t.get('ws_urgent', '#bf616a')

    css_content = f"""/* ==============================================================================
 * {t.get('name', 'Theme')} GTK3/4 & Thunar Theme Tokens
 * Generated by central theme-engine
 * ============================================================================== */

@define-color theme_bg {bg};
@define-color theme_fg {fg};
@define-color theme_sidebar {capsule_bg};
@define-color theme_surface {capsule_hover};
@define-color theme_border {border};
@define-color theme_accent {accent};
@define-color theme_selected_bg {accent};
@define-color theme_selected_fg {bg};
@define-color theme_urgent {urgent};

/* Base Window and Backgrounds */
window,
.background {{
    background-color: @theme_bg;
    color: @theme_fg;
}}

/* Base typography */
* {{
    font-family: "Maple Mono", "SymbolsNF", monospace;
    -gtk-secondary-caret-color: @theme_accent;
}}

/* Thunar Specific Styling */
ThunarWindow {{
    background-color: @theme_bg;
    color: @theme_fg;
}}

/* Thunar Side Pane (Shortcuts / Places) */
ThunarWindow .sidebar,
ThunarShortcutsPane,
ThunarTreePane,
.sidebar list {{
    background-color: @theme_sidebar;
    color: @theme_fg;
    border-right: 1px solid @theme_border;
}}

ThunarWindow .sidebar row:selected {{
    background-color: @theme_accent;
    color: @theme_bg;
    font-weight: bold;
    border-radius: 4px;
}}

ThunarWindow .sidebar row:hover {{
    background-color: @theme_surface;
}}

/* Thunar Main File View */
ThunarStandardView,
ThunarIconView,
ThunarDetailsView,
ThunarCompactView,
.view {{
    background-color: @theme_bg;
    color: @theme_fg;
}}

.view:selected,
.view row:selected,
iconview:selected {{
    background-color: @theme_accent;
    color: @theme_bg;
    border-radius: 4px;
}}

.view row:hover,
iconview:hover {{
    background-color: @theme_surface;
}}

/* Header bar, Toolbar, Location Bar */
headerbar,
toolbar,
.primary-toolbar {{
    background-color: @theme_surface;
    color: @theme_fg;
    border-bottom: 1px solid @theme_border;
    padding: 4px 6px;
}}

/* Path / Breadcrumb Bar Buttons */
headerbar button,
toolbar button,
.path-bar button {{
    background-color: transparent;
    color: @theme_fg;
    border-radius: 4px;
    border: none;
    padding: 4px 8px;
}}

headerbar button:hover,
toolbar button:hover,
.path-bar button:hover {{
    background-color: @theme_border;
    color: #FFFFFF;
}}

headerbar button:checked,
toolbar button:checked,
.path-bar button:checked {{
    background-color: @theme_accent;
    color: @theme_bg;
}}

/* Text Inputs / Path Entry */
entry {{
    background-color: @theme_surface;
    color: @theme_fg;
    border: 1px solid @theme_border;
    border-radius: 4px;
    padding: 4px 8px;
}}

entry:focus {{
    border-color: @theme_accent;
    box-shadow: 0 0 0 1px @theme_accent;
}}

/* Context Menus & Popovers */
menu,
popover {{
    background-color: @theme_surface;
    color: @theme_fg;
    border: 1px solid @theme_border;
    border-radius: 6px;
    padding: 4px;
}}

menu menuitem {{
    padding: 6px 10px;
    border-radius: 4px;
}}

menu menuitem:hover {{
    background-color: @theme_accent;
    color: @theme_bg;
}}

/* Status Bar */
statusbar {{
    background-color: @theme_surface;
    color: @theme_fg;
    border-top: 1px solid @theme_border;
    padding: 2px 8px;
    font-size: 11px;
}}

/* Scrollbars */
scrollbar {{
    background-color: transparent;
}}

scrollbar slider {{
    background-color: @theme_border;
    border-radius: 6px;
    min-width: 6px;
    min-height: 6px;
}}

scrollbar slider:hover {{
    background-color: @theme_accent;
}}
"""
    with open(GTK_CSS, "w") as f:
        f.write(css_content)

def update_btop(t):
    os.makedirs(BTOP_THEMES_DIR, exist_ok=True)
    theme_file = os.path.join(BTOP_THEMES_DIR, "wm.theme")
    content = f"""# btop theme generated by theme-engine for {t.get('name', 'Theme')}
theme[main_bg]="{t.get('background', '#2e3440')}"
theme[main_fg]="{t.get('foreground', '#d8dee9')}"
theme[title]="{t.get('accent', '#88c0d0')}"
theme[hi_fg]="{t.get('accent_alt', t.get('accent', '#81a1c1'))}"
theme[selected_bg]="{t.get('capsule_hover', '#3b4252')}"
theme[selected_fg]="{t.get('foreground', '#eceff4')}"
theme[inactive_fg]="{t.get('border', '#4c566a')}"
theme[proc_misc]="{t.get('clock', '#b48ead')}"
theme[cpu_box]="{t.get('border', '#4c566a')}"
theme[mem_box]="{t.get('border', '#4c566a')}"
theme[net_box]="{t.get('border', '#4c566a')}"
theme[proc_box]="{t.get('border', '#4c566a')}"
theme[div_line]="{t.get('border', '#4c566a')}"
theme[temp_start]="{t.get('vol', '#a3be8c')}"
theme[temp_mid]="{t.get('net', '#ebcb8b')}"
theme[temp_end]="{t.get('ws_urgent', '#bf616a')}"
theme[cpu_start]="{t.get('vol', '#a3be8c')}"
theme[cpu_mid]="{t.get('net', '#ebcb8b')}"
theme[cpu_end]="{t.get('ws_urgent', '#bf616a')}"
theme[free_start]="{t.get('vol', '#a3be8c')}"
theme[free_mid]="{t.get('net', '#ebcb8b')}"
theme[free_end]="{t.get('ws_urgent', '#bf616a')}"
theme[cached_start]="{t.get('accent', '#88c0d0')}"
theme[cached_mid]="{t.get('clock', '#b48ead')}"
theme[cached_end]="{t.get('ws_urgent', '#bf616a')}"
theme[available_start]="{t.get('accent', '#88c0d0')}"
theme[available_mid]="{t.get('vol', '#a3be8c')}"
theme[available_end]="{t.get('net', '#ebcb8b')}"
theme[used_start]="{t.get('accent', '#88c0d0')}"
theme[used_mid]="{t.get('net', '#ebcb8b')}"
theme[used_end]="{t.get('ws_urgent', '#bf616a')}"
theme[download_start]="{t.get('accent', '#88c0d0')}"
theme[download_mid]="{t.get('clock', '#b48ead')}"
theme[download_end]="{t.get('ws_urgent', '#bf616a')}"
theme[upload_start]="{t.get('net', '#ebcb8b')}"
theme[upload_mid]="{t.get('accent', '#88c0d0')}"
theme[upload_end]="{t.get('clock', '#b48ead')}"
"""
    with open(theme_file, "w") as f:
        f.write(content)

    if os.path.isfile(BTOP_CONF):
        with open(BTOP_CONF, "r") as f:
            bconf = f.read()
        if 'color_theme = "wm"' not in bconf and 'color_theme = "wm.theme"' not in bconf:
            bconf = re.sub(r'color_theme = ".*?"', 'color_theme = "wm"', bconf)
            with open(BTOP_CONF, "w") as f:
                f.write(bconf)

def update_fastfetch(t):
    os.makedirs(os.path.dirname(FASTFETCH_CONF), exist_ok=True)
    conf = {
        "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
        "logo": {
            "type": "small",
            "padding": {"top": 1, "left": 1, "right": 2}
        },
        "display": {
            "separator": " 󰅂 ",
            "color": {
                "keys": "cyan",
                "title": "blue"
            }
        },
        "modules": [
            "title",
            "separator",
            {"type": "os", "key": "󰣚 OS"},
            {"type": "kernel", "key": "󰌽 KR"},
            {"type": "wm", "key": "󱂬 WM"},
            {"type": "terminal", "key": "󰞷 TM"},
            {"type": "uptime", "key": "󰅐 UP"},
            {"type": "memory", "key": "󰍛 MEM"},
            "break",
            "colors"
        ]
    }
    try:
        with open(FASTFETCH_CONF, "w") as f:
            json.dump(conf, f, indent=2)
    except Exception:
        pass

def broadcast_term_colors(t):
    """Broadcast OSC color sequences to open PTY terminals."""
    bg = t.get('background', '#2e3440')
    fg = t.get('foreground', '#d8dee9')
    # OSC 10: set foreground, OSC 11: set background
    osc_seq = f"\033]10;{fg}\007\033]11;{bg}\007"
    for pt in glob.glob("/dev/pts/[0-9]*"):
        try:
            # Only write if user has write access
            if os.access(pt, os.W_OK):
                with open(pt, "w", errors="ignore") as f:
                    f.write(osc_seq)
        except Exception:
            pass

def reload_subsystems():
    """Live reload compositor, bar, and notification daemon without session restart."""
    # 1. Waybar
    subprocess.run(["pkill", "-USR2", "waybar"], stderr=subprocess.DEVNULL)

    # 2. Mako
    subprocess.run(["makoctl", "reload"], stderr=subprocess.DEVNULL)

    # 3. MangoWC
    subprocess.run(["mmsg", "dispatch", "reload_config"], stderr=subprocess.DEVNULL)

def apply_theme(theme_id, set_wallpaper=True):
    theme = load_theme(theme_id)

    # 1. Waybar CSS & JSON
    with open(os.path.join(THEMES_DIR, "palette.css"), "w") as f:
        f.write(generate_waybar_css(theme))
    with open(os.path.join(THEMES_DIR, "palette.json"), "w") as f:
        json.dump(theme, f, indent=2)
    with open(os.path.join(CACHE_DIR, "wm-palette.json"), "w") as f:
        json.dump(theme, f, indent=2)

    # 2. Rofi RASI
    rofi_rasi = generate_rofi_rasi(theme)
    with open(os.path.join(THEMES_DIR, "palette.rasi"), "w") as f:
        f.write(rofi_rasi)
    with open(os.path.join(REPO_DIR, "rofi", "colors.rasi"), "w") as f:
        f.write(rofi_rasi)

    # 3. Foot INI
    with open(os.path.join(THEMES_DIR, "foot.ini"), "w") as f:
        f.write(generate_foot_ini(theme))

    # 4. Mako Config
    with open(MAKO_CONF, "w") as f:
        f.write(generate_mako_conf(theme))

    # 5. Shell Environment
    with open(os.path.join(THEMES_DIR, "palette.env"), "w") as f:
        f.write(generate_shell_env(theme))

    # 6. MangoWC Configuration
    update_mango_conf(theme)

    # 7. GTK 3 & 4
    update_gtk_css(theme)

    # 8. btop
    update_btop(theme)

    # 9. Fastfetch
    update_fastfetch(theme)

    # 10. Update state tracking
    with open(os.path.join(THEMES_DIR, "current"), "w") as f:
        f.write(f"{theme_id}\n")
    mode = "dynamic" if theme_id == "dynamic" else "static"
    with open(os.path.join(THEMES_DIR, "current_mode"), "w") as f:
        f.write(f"{mode}\n")

    # 11. Optionally switch wallpaper if defined and requested
    if set_wallpaper and theme_id != "dynamic":
        wp_name = theme.get("wallpaper")
        if wp_name:
            wp_path = os.path.join(REPO_DIR, "wallpapers", wp_name)
            if os.path.isfile(wp_path):
                wp_manager = os.path.join(SCRIPT_DIR, "wallpaper-manager")
                if os.path.isfile(wp_manager) and os.access(wp_manager, os.X_OK):
                    subprocess.run([wp_manager, "set", wp_path, "--skip-theme"], stderr=subprocess.DEVNULL)

    # 12. Broadcast colors to open terminals
    broadcast_term_colors(theme)

    # 13. Live reload services
    reload_subsystems()

    # 14. Notification
    theme_name = theme.get("name", theme_id)
    subprocess.run([
        "notify-send",
        "-h", "string:x-canonical-private-synchronous:wm-theme",
        "Theme Applied",
        f"Active desktop theme: {theme_name}"
    ], stderr=subprocess.DEVNULL)

    print(f"Successfully applied theme: {theme_name} ({theme_id})")

def main():
    if len(sys.argv) < 2:
        print("Usage: theme-engine.py <theme_id> [--no-wallpaper]")
        sys.exit(1)

    theme_id = sys.argv[1].strip()
    set_wp = "--no-wallpaper" not in sys.argv

    try:
        apply_theme(theme_id, set_wallpaper=set_wp)
    except Exception as e:
        print(f"Error applying theme '{theme_id}': {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
